name: amber
description: A collaborative content mash-up platform as a safe, creative space for people to share original media content, facilitate mixing-and-matching others’ content (possibly with their own), share their mash-up creations, and work with other people live during the creation and sharing processes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.5
  image: ^3.1.1
  http: ^0.13.4
  timeago: ^3.1.0
  provider: ^6.0.1
  flutter_svg: ^1.0.0
  google_fonts: ^2.2.0
  path_provider: ^2.0.8
  firebase_auth: ^3.3.4
  flutter_login: ^3.1.0
  firebase_core: ^1.10.6
  image_picker: ^0.8.4+4
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.5
  email_validator: ^2.0.1
  flutter_slidable: ^1.2.0
  firebase_storage: ^10.2.5
  convex_bottom_bar: ^3.0.0
  modal_bottom_sheet: ^2.0.0
  flutter_easyloading: ^3.0.3
  cached_network_image: ^3.2.0
  multi_select_flutter: ^4.0.0
  scrollable_positioned_list: ^0.2.3
#  flutter_native_splash: ^1.3.2
#
#flutter_native_splash:
#  color: "#FFBF00"
#  image: assets/logo.png
#  android: true
#  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
