name: amber
description: A collaborative content mash-up platform as a safe, creative space for people to share original media content, facilitate mixing-and-matching others’ content (possibly with their own), share their mash-up creations, and work with other people live during the creation and sharing processes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid:
  hive:
  flutter_firebase_chat_core:
#  flutter_nsfw: ^0.0.4
  mime: ^1.0.1
  open_file: ^3.2.1
  mailer: ^5.1.0
  lottie:
  timeago:
  card_swiper:
  carousel_slider: ^4.0.0
  hive_flutter:
  google_fonts:
  path_provider:
  provider: ^6.0.2
  firebase_auth:
  flutter_login:
  flutter_quill: 4.0.0
  firebase_core:
  image_picker:
  flutter_chat_ui:
  file_picker: ^4.5.1
  flutter_colorpicker:
  cloud_firestore:
  email_validator:
  flutter_slidable:
  firebase_storage:
  convex_bottom_bar:
  modal_bottom_sheet:
  flutter_easyloading:
  multi_select_flutter:
  scrollable_positioned_list:
  material_floating_search_bar:
  shimmer:
  sentry_flutter: ^6.3.0
#  flutter_native_splash: ^1.3.2
#
#flutter_native_splash:
#  color: "#FFBF00"
#  image: assets/logo.png
#  android: true
#  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test:
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/create/
    - assets/layouts/
    - assets/hashtags/
