name: amber
description: A collaborative content mash-up platform as a safe, creative space for people to share original media content, facilitate mixing-and-matching others’ content (possibly with their own), share their mash-up creations, and work with other people live during the creation and sharing processes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  provider: ^6.0.2
  uuid: ^3.0.6
  hive: ^2.0.6
  flutter_firebase_chat_core: ^1.5.2
#  flutter_nsfw: ^0.0.5
  mime: ^1.0.1
  open_file: ^3.2.1
  lottie: ^1.2.2
  timeago: ^3.2.2
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.20
  hive_flutter: ^1.1.0
  google_fonts: ^2.3.1
  #  path_provider: ^2.0.9
  flutter_login: ^3.2.0
  flutter_quill: ^4.0.9
  image_picker: ^0.8.4+11
  flutter_chat_ui: ^1.5.5
  file_picker: ^4.5.1
  flutter_colorpicker: ^1.0.3
  email_validator: ^2.0.1
  flutter_slidable: ^1.2.0
  firebase_storage: ^10.2.9
  convex_bottom_bar: ^3.0.0
  modal_bottom_sheet: ^2.0.1
  flutter_easyloading: ^3.0.3
  multi_select_flutter: ^4.1.2
  scrollable_positioned_list: ^0.2.3
  shimmer: ^2.0.0
  sentry_flutter: ^6.3.0
  cached_network_image:
  card_swiper:
  o_popup: ^1.0.1
  styled_text:
#  flutter_native_splash: ^1.3.2
#
#flutter_native_splash:
#  color: "#FFBF00"
#  image: assets/logo.png
#  android: true
#  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test:
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/create/
    - assets/layouts/
    - assets/hashtags/
    - assets/discover/
