import 'package:flutter/material.dart';

class Hashtag {
  final int id;
  final String name;

  Hashtag({Key? key, required this.id, required this.name});

  static final List<Hashtag> hashtags = [
    Hashtag(id: 1, name: "#love"),
    Hashtag(id: 2, name: "#instagood"),
    Hashtag(id: 3, name: "#photooftheday"),
    Hashtag(id: 4, name: "#fashion"),
    Hashtag(id: 5, name: "#beautiful"),
    Hashtag(id: 6, name: "#happy"),
    Hashtag(id: 7, name: "#cute"),
    Hashtag(id: 8, name: "#tbt"),
    Hashtag(id: 9, name: "#like4like"),
    Hashtag(id: 10, name: "#followme"),
    Hashtag(id: 11, name: "#picoftheday"),
    Hashtag(id: 12, name: "#follow"),
    Hashtag(id: 13, name: "#me"),
    Hashtag(id: 14, name: "#selfie"),
    Hashtag(id: 15, name: "#summer"),
    Hashtag(id: 16, name: "#art"),
    Hashtag(id: 17, name: "#instadaily"),
    Hashtag(id: 18, name: "#friends"),
    Hashtag(id: 19, name: "#repost"),
    Hashtag(id: 20, name: "#nature"),
    Hashtag(id: 21, name: "#girl"),
    Hashtag(id: 22, name: "#fun"),
    Hashtag(id: 23, name: "#style"),
    Hashtag(id: 24, name: "#smile"),
    Hashtag(id: 25, name: "#food"),
    Hashtag(id: 26, name: "#instalike"),
    Hashtag(id: 27, name: "#likeforlike"),
    Hashtag(id: 28, name: "#family"),
    Hashtag(id: 29, name: "#travel"),
    Hashtag(id: 30, name: "#fitness"),
    Hashtag(id: 31, name: "#euro2020"),
    Hashtag(id: 32, name: "#tagsforlikes"),
    Hashtag(id: 33, name: "#follow4follow"),
    Hashtag(id: 34, name: "#nofilter"),
    Hashtag(id: 35, name: "#life"),
    Hashtag(id: 36, name: "#beauty"),
    Hashtag(id: 37, name: "#amazing"),
    Hashtag(id: 38, name: "#instamood"),
    Hashtag(id: 39, name: "#igers"),
    Hashtag(id: 40, name: "#instagram"),
    Hashtag(id: 41, name: "#photo"),
    Hashtag(id: 42, name: "#music"),
    Hashtag(id: 43, name: "#photography"),
    Hashtag(id: 44, name: "#makeup"),
    Hashtag(id: 45, name: "#dog"),
    Hashtag(id: 46, name: "#beach"),
    Hashtag(id: 47, name: "#sunset"),
    Hashtag(id: 48, name: "#model"),
    Hashtag(id: 49, name: "#foodporn"),
    Hashtag(id: 50, name: "#motivation"),
    Hashtag(id: 51, name: "#followforfollow"),
    Hashtag(id: 52, name: "#sky"),
    Hashtag(id: 53, name: "#lifestyle"),
    Hashtag(id: 54, name: "#design"),
    Hashtag(id: 55, name: "#gym"),
    Hashtag(id: 56, name: "#f4f"),
    Hashtag(id: 57, name: "#toofunny"),
    Hashtag(id: 58, name: "#cat"),
    Hashtag(id: 59, name: "#handmade"),
    Hashtag(id: 60, name: "#hair"),
    Hashtag(id: 61, name: "#vscocam"),
    Hashtag(id: 62, name: "#bestoftheday"),
    Hashtag(id: 63, name: "#vsco"),
    Hashtag(id: 64, name: "#funny"),
    Hashtag(id: 65, name: "#dogsofinstagram"),
    Hashtag(id: 66, name: "#drawing"),
    Hashtag(id: 67, name: "#artist"),
    Hashtag(id: 68, name: "#f4fl"),
    Hashtag(id: 69, name: "#flowers"),
    Hashtag(id: 70, name: "#baby"),
    Hashtag(id: 71, name: "#wedding"),
    Hashtag(id: 72, name: "#girls"),
    Hashtag(id: 73, name: "#instapic"),
    Hashtag(id: 74, name: "#pretty"),
    Hashtag(id: 75, name: "#photographer"),
    Hashtag(id: 76, name: "#instafood"),
    Hashtag(id: 77, name: "#party"),
    Hashtag(id: 78, name: "#inspiration"),
    Hashtag(id: 79, name: "#lol"),
    Hashtag(id: 80, name: "#cool"),
    Hashtag(id: 81, name: "#workout"),
    Hashtag(id: 82, name: "#likeforfollow"),
    Hashtag(id: 83, name: "#swag"),
    Hashtag(id: 84, name: "#fit"),
    Hashtag(id: 85, name: "#healthy"),
    Hashtag(id: 86, name: "#yummy"),
    Hashtag(id: 87, name: "#blackandwhite"),
    Hashtag(id: 88, name: "#foodie"),
    Hashtag(id: 89, name: "#moda"),
    Hashtag(id: 90, name: "#home"),
    Hashtag(id: 91, name: "#christmas"),
    Hashtag(id: 92, name: "#black"),
    Hashtag(id: 93, name: "#memes"),
    Hashtag(id: 94, name: "#winter"),
    Hashtag(id: 95, name: "#pink"),
    Hashtag(id: 96, name: "#sea"),
    Hashtag(id: 97, name: "#landscape"),
    Hashtag(id: 98, name: "#blue"),
    Hashtag(id: 99, name: "#london"),
    Hashtag(id: 100, name: "#holiday"),
  ];
}
